name: Sync @next with @latest
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'cheqd'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_ref: ${{ github.ref }}
          target_branch: 'next'
          commit_message_template: 'chore(ci): merge main into next'
